import { StrictMode, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { createRootRoute, createRoute, createRouter, Outlet, RouterProvider, useRouterState } from '@tanstack/react-router';
import PrivacyPolicy from './PrivacyPolicy';
import './style.css';
const phone = 'tel:+918303807051';
function Call({light=false}:{light?:boolean}) {return <a className={`button ${light?'light':''}`} href={phone}>Call +91 83038 07051 <span aria-hidden="true">↗</span></a>}
function Header({company}:{company:boolean}){return <header><a className="brand" href={company?'https://gandivalabs.com/in':'https://karobaar.gandivalabs.com'}>{company?'Gandiva Labs':'karobaar'}</a><nav aria-label="Main navigation">{company?<><a href="#company-product">Our product</a><a href="#company-contact">Contact</a></>:<><a href="#product">Product</a><a href="https://gandivalabs.com/in">Gandiva Labs ↗</a></>}<a className="nav-call" href={phone}>Call us ↗</a></nav></header>}
function Footer({company}:{company:boolean}){return <footer><a href={company?'https://karobaar.gandivalabs.com':'https://gandivalabs.com/in'}>{company?'Explore Karobaar ↗':'A product by Gandiva Labs ↗'}</a><span>© {new Date().getFullYear()} {company?'Gandiva Labs':'Karobaar'}</span><a href="https://karobaar.gandivalabs.com/privacy-policy">{company?'Karobaar privacy policy':'Privacy policy'}</a></footer>}
function Layout(){const path=useRouterState({select:s=>s.location.pathname});const company=location.hostname==='gandivalabs.com'||path==='/in';return <><a className="skip" href="#main">Skip to content</a><Header company={company}/><Outlet/><Footer company={company}/></>}
const customers=['LocalLogic Media','Local Logic Studios','Square','One undisclosed company'];
function Customers(){return <section className="customers" aria-labelledby="customers-title"><div><span className="eyebrow">INTERNAL USE / 04 COMPANIES</span><h2 id="customers-title">Built alongside teams<br/>doing the work.</h2><p>Karobaar is currently used inside four companies while we prepare for public launch.</p></div><div className="customer-list">{customers.map((name,index)=><div key={name}><span>0{index+1}</span><strong>{name}</strong>{index===3&&<small>NAME UNDISCLOSED</small>}</div>)}</div><div className="customer-stats">{[['1,700+','transactions recorded'],['900+','numbered bills'],['600+','party records'],['150+','leads recorded']].map(([value,label])=><p key={label}><strong>{value}</strong><span>{label}</span></p>)}<small>Aggregate production records across the workspace. Usage varies by company; transaction totals include drafts and payment records.</small></div></section>}
const lifecycle=[['01','Leads & pipelines','Build custom stages, move opportunities visually and keep every follow-up visible.'],['02','Unified parties','Keep customer details, conversations, quotations, invoices and activity in one profile.'],['03','Quotations & catalog','Pull products from your catalog and prepare accurate, professional quotations quickly.'],['04','Billing & collection','Turn approved quotations into GST-ready invoices and follow payment status.']];
const capabilities=[['01','WhatsApp-connected CRM','Bring messages and calls into the sales pipeline so enquiries do not disappear in chat threads.'],['02','Custom pipeline builder','Shape stages and workflows around the way your team actually sells.'],['03','Party management','Give the team one current record for every customer, supplier and interaction.'],['04','Product catalog & quotations','Keep products, pricing details and quotations connected to each opportunity.'],['05','GST-ready invoicing','Create compliant invoices from active deals without rebuilding the same information.'],['06','Attendance records','Keep employee attendance records alongside the rest of your daily operations.'],['07','Roles & audit trail','Control who can see and change information, with activity logs across the organization.'],['08','Analytics & team activity','Review pipeline movement, win rates, follow-ups and business activity in one view.'],['09','Mobile sync','Keep the team connected to the same workspace across supported devices.'],['10','Multi-branch operations','Coordinate pipelines, people and day-to-day work across multiple locations.']];
function Landing(){useEffect(()=>{document.title='Karobaar — A workspace that cares for your business'},[]);return <main id="main"><section className="hero"><div className="eyebrow">KAROBAAR / BUSINESS WORKSPACE</div><h1>A workspace that cares<br className="desktop"/> <span>for your business.</span></h1><p className="hero-copy">Bring leads, customer records, quotations and billing together. Beautifully organized, so your team can focus on the people behind the business.</p><div className="hero-actions"><Call/><span>Call to see the product and discuss your team’s needs.</span></div><div className="proof"><span className="proof-number">04</span><p>Currently used internally by <strong>4 companies.</strong><br/><span>Public launch coming soon.</span></p></div></section><Customers/><section className="relief"><span className="eyebrow">THE KAROBAAR DIFFERENCE</span><h2>Stop fighting your tools.</h2><p>Leads in chat threads. Customer details in spreadsheets. Invoices in another tool. Karobaar brings the work together, so the next conversation starts with the full picture.</p></section><section className="lifecycle" id="product"><div className="section-heading"><span className="eyebrow">02 / THE SALES LIFECYCLE</span><h2>One record of the work,<br/>from lead to invoice.</h2></div><div className="lifecycle-grid">{lifecycle.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section><section className="features"><div className="section-heading"><span className="eyebrow">03 / WHAT'S INSIDE</span><h2>The tools your team uses<br/>to run the day.</h2></div><div className="feature-list">{capabilities.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section><section className="roadmap"><span className="eyebrow">04 / WHAT'S NEXT</span><div><span className="tag">PLANNED INTEGRATION</span><h2>Voice agents are on the roadmap.</h2><p>We plan to integrate voice agents for customer conversations and operational workflows. This is on our roadmap and is not available yet.</p></div></section><section className="contact"><span className="eyebrow">EARLY CONVERSATIONS WELCOME</span><h2>See how Karobaar fits your business.</h2><p>Karobaar is in internal use today. Call us to see the product<br className="desktop"/> and talk about what your team needs before public launch.</p><Call light/></section></main>}
function Company(){useEffect(()=>{document.title='Gandiva Labs — Software for the everyday business'},[]);return <main id="main" className="company"><span className="eyebrow">GANDIVA LABS / INDIA</span><h1>Software for<br/><span>everyday business.</span></h1><p className="hero-copy">Gandiva Labs builds practical tools for teams managing customers, sales and daily operations.</p><section className="company-product" id="company-product"><span className="eyebrow">OUR PRODUCT / 01</span><h2>Karobaar</h2><p>A shared workspace for leads, customers, quotations and daily operations. Currently used internally by 4 companies. Public launch coming soon.</p><a className="text-link" href="https://karobaar.gandivalabs.com">Explore Karobaar ↗</a></section><section className="company-contact" id="company-contact"><h2>Let's talk about your business.</h2><Call/></section></main>}
function Privacy(){useEffect(()=>{document.title='Privacy policy — Karobaar'},[]);return <main id="main" className="policy"><a className="text-link" href="/">← Back to Karobaar</a><PrivacyPolicy/></main>}
const rootRoute=createRootRoute({component:Layout});
const indexRoute=createRoute({getParentRoute:()=>rootRoute,path:'/',component:()=>location.hostname==='gandivalabs.com'?<Company/>:<Landing/>});
const companyRoute=createRoute({getParentRoute:()=>rootRoute,path:'/in',component:Company});
const policyRoute=createRoute({getParentRoute:()=>rootRoute,path:'/privacy-policy',component:Privacy});
const router=createRouter({routeTree:rootRoute.addChildren([indexRoute,companyRoute,policyRoute]),defaultNotFoundComponent:()=> <main id="main" className="company"><h1>Page not found.</h1><a href="/">Back to home →</a></main>});
createRoot(document.getElementById('root')!).render(<StrictMode><RouterProvider router={router}/></StrictMode>);
