import { StrictMode, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { createRootRoute, createRoute, createRouter, Outlet, RouterProvider } from '@tanstack/react-router';
import PrivacyPolicy from './PrivacyPolicy';
import './style.css';
const phone = 'tel:+918303807051';
function Call({light=false}:{light?:boolean}) {return <a className={`button ${light?'light':''}`} href={phone}>Call +91 83038 07051 <span aria-hidden="true">↗</span></a>}
function Header(){return <header><a className="brand" href="https://karobaar.gandivalabs.com"><span className="mark">k</span>karobaar<span className="brand-dot">®</span></a><nav aria-label="Main navigation"><a href="/#product">The product</a><a href="https://gandivalabs.com/in">Gandiva Labs ↗</a><a className="nav-call" href={phone}>Let's talk ↗</a></nav></header>}
function Footer(){return <footer><a href="https://gandivalabs.com/in">A product by Gandiva Labs ↗</a><span>© {new Date().getFullYear()} Karobaar</span><a href="/privacy-policy">Privacy policy</a></footer>}
function Layout(){return <><a className="skip" href="#main">Skip to content</a><Header/><Outlet/><Footer/></>}
const stages=[{name:'New enquiry',className:'new',items:[['A new opportunity','Capture the details'],['A returning customer','Keep the context']]},{name:'In conversation',className:'conversation',items:[['The right solution','Track the next step']]},{name:'Quotation sent',className:'quoted',items:[['Ready for review','Keep work moving']]}];
function ProductBoard(){return <div className="board" aria-label="Illustrative Karobaar workflow"><div className="board-top"><span><span className="mini-mark">k</span> Workspace</span><span className="preview-label">WORKFLOW PREVIEW</span><span className="avatar">K</span></div><div className="board-content"><aside><b>Workspace</b><span className="selected">▦ &nbsp; Sales pipeline</span><span>◉ &nbsp; Customers</span><span>▤ &nbsp; Quotations</span><span>□ &nbsp; Catalog</span></aside><div className="pipeline"><div className="pipeline-title"><h3>Every opportunity.<br/>A clear next step.</h3><span>Sales pipeline ↗</span></div><div className="columns">{stages.map(s=><div className="column" key={s.name}><div className="stage"><i className={s.className}/>{s.name}<span>{s.items.length}</span></div>{s.items.map(([name,detail])=><div className="lead" key={name}><span className="lead-label">CUSTOMER ENQUIRY</span><h4>{name}</h4><p>{detail}</p><div className="lead-bottom"><span>Follow-up →</span><i/></div></div>)}</div>)}</div></div></div><div className="board-bottom"><span><i/> One shared view of the work</span><span>Illustrative workflow · sample entries</span></div></div>}
function Landing(){useEffect(()=>{document.title='Karobaar — Keep business moving'},[]);return <main id="main"><section className="hero"><div className="eyebrow"><i/> BUILT FOR THE EVERYDAY BUSINESS</div><h1>Less chasing.<br/>More <em>karobaar.</em></h1><p className="hero-copy">Your leads, customers and quotations.<br/>One workspace to keep business moving.</p><div className="hero-actions"><Call/><span>Talk to the team.<br/>See if Karobaar fits your business.</span></div><div className="proof"><span className="proof-number">04</span><p>Currently used internally by <strong>4 companies.</strong><br/><span>Public launch coming soon.</span></p></div><div className="hero-note">काम आगे बढ़ाओ.<span>KEEP BUSINESS MOVING.</span></div></section><section className="product" id="product"><div className="section-heading"><span className="eyebrow">01 / THE WORKSPACE</span><p>From the first enquiry<br/>to the next quotation.</p></div><ProductBoard/></section><section className="features"><div className="section-heading"><span className="eyebrow">02 / A CLEARER WORKDAY</span><h2>Keep the details together.<br/>Keep the team in sync.</h2></div><div className="feature-list">{[['01','Know what needs a follow-up.','Organize opportunities in a sales pipeline, so your team knows where each conversation stands.'],['02','Keep your customer context.','Bring party details and business history into one place, ready for the next conversation.'],['03','Move from enquiry to quotation.','Keep your product catalog and quotations close to the people and opportunities they belong to.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section><section className="roadmap"><span className="eyebrow">03 / WHAT'S NEXT</span><div><span className="tag">PLANNED INTEGRATION</span><h2>A voice for the<br/>next stage of business.</h2><p>We plan to integrate voice agents for customer conversations and operational workflows. This is on our roadmap and is not available yet.</p></div></section><section className="contact"><span className="eyebrow">EARLY CONVERSATIONS WELCOME</span><h2>Your business has a rhythm.<br/>Let's find where we fit.</h2><p>Karobaar is in internal use today. Call us to see the product<br className="desktop"/> and talk about what your team needs before public launch.</p><Call light/></section></main>}
function Company(){useEffect(()=>{document.title='Gandiva Labs — Software for the everyday business'},[]);return <main id="main" className="company"><span className="eyebrow">GANDIVA LABS / INDIA</span><h1>Built around<br/><em>real work.</em></h1><p className="hero-copy">We build software for the people<br/>who keep businesses running.</p><section className="company-product"><span className="eyebrow">OUR PRODUCT / 01</span><h2>Karobaar</h2><p>A shared workspace for leads, customers, quotations and daily operations. Currently used internally by 4 companies. Public launch coming soon.</p><a className="text-link" href="https://karobaar.gandivalabs.com">Explore Karobaar ↗</a></section><section className="company-contact"><h2>Let's talk about your business.</h2><Call/></section></main>}
function Privacy(){useEffect(()=>{document.title='Privacy policy — Karobaar'},[]);return <main id="main" className="policy"><a className="text-link" href="/">← Back to Karobaar</a><PrivacyPolicy/></main>}
const rootRoute=createRootRoute({component:Layout});
const indexRoute=createRoute({getParentRoute:()=>rootRoute,path:'/',component:()=>location.hostname==='gandivalabs.com'?<Company/>:<Landing/>});
const companyRoute=createRoute({getParentRoute:()=>rootRoute,path:'/in',component:Company});
const policyRoute=createRoute({getParentRoute:()=>rootRoute,path:'/privacy-policy',component:Privacy});
const router=createRouter({routeTree:rootRoute.addChildren([indexRoute,companyRoute,policyRoute]),defaultNotFoundComponent:()=> <main id="main" className="company"><h1>Page not found.</h1><a href="/">Back to home →</a></main>});
createRoot(document.getElementById('root')!).render(<StrictMode><RouterProvider router={router}/></StrictMode>);
